/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-06-17 06:00:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>상품</title>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div id=\"divPage\">\r\n");
      out.write("      <div id=\"divMenu\"></div>\r\n");
      out.write("      <div id=\"divHeader\">\r\n");
      out.write("         <h2>상 품 목 록</h2>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"divCondition\">\r\n");
      out.write("         <div id=\"divSearch\">\r\n");
      out.write("            <select id=\"selKey\">\r\n");
      out.write("               <option value=\"product_code\">상품코드</option>\r\n");
      out.write("               <option value=\"product_name\">상품명</option>\r\n");
      out.write("               <option value=\"company\">제조사</option>\r\n");
      out.write("               \r\n");
      out.write("            </select> <input type=\"text\" id=\"txtWord\">\r\n");
      out.write("            <select id=\"selPerpage\">\r\n");
      out.write("               <option value=\"3\">3행</option>\r\n");
      out.write("               <option value=\"5\">5행</option>\r\n");
      out.write("               <option value=\"10\">10행</option>\r\n");
      out.write("            </select> <input type=\"button\" id=\"btnSearch\" value=\"검색\"> <span\r\n");
      out.write("               style=\"font-size: 12px;\">검색수: <b id=\"count\"></b>건\r\n");
      out.write("            </span>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div id=\"divSort\">\r\n");
      out.write("            <select id=\"selOrder\">\r\n");
      out.write("               <option value=\"product_code\">상품코드</option>\r\n");
      out.write("               <option value=\"product_name\">상품명</option>\r\n");
      out.write("               <option value=\"company\">제조사</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <select id=\"selDesc\">\r\n");
      out.write("               <option value=\"\">오름차순</option>\r\n");
      out.write("               <option value=\"desc\">내림차순</option>\r\n");
      out.write("            </select>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("       <table id=\"tbl\"></table>    \r\n");
      out.write("         <script id=\"temp\" type=\"text/x-handlebars-template\">  \r\n");
      out.write("          <tr class=\"title\"> \r\n");
      out.write("\t\t\t<td><input type=\"checkbox\" id=\"chkAll\"></td>\r\n");
      out.write("\t\t\t<td>상품코드</td>     \r\n");
      out.write("\t\t\t<td width=130>카테고리</td>      \r\n");
      out.write("            <td width=130>상품명</td> \r\n");
      out.write("            <td width=130>가격:</td>\r\n");
      out.write("\t\t\t<td width=130>제조사</td>\r\n");
      out.write("\t\t\t<td width=130>제조일</td>\r\n");
      out.write("\t\t\t<td width=130>폐기일</td>\r\n");
      out.write("\t\t\t<td width=130>이미지</td>\r\n");
      out.write("\t\t  \t<td>버튼</td>\r\n");
      out.write("          </tr>       \r\n");
      out.write("         {{#each array}}       \r\n");
      out.write("          <tr class=\"row\">\r\n");
      out.write("\t\t\t<td><input type=\"checkbox\" class=\"chk\"></td>\r\n");
      out.write("\t\t\t<td class=\"product_code\">{{category_code}}{{product_code}}</td>\r\n");
      out.write("\t\t\t<td class=\"category_name\">{{category_name}}</td>                \r\n");
      out.write("            <td class=\"product_name\">{{product_name}}</td>   \r\n");
      out.write("            <td class=\"product_price\">{{product_price}}</td> \r\n");
      out.write(" \t\t\t<td class=\"company\">{{company}}</td> \r\n");
      out.write(" \t\t\t<td class=\"product_date\">{{product_date}}</td> \r\n");
      out.write(" \t\t\t<td class=\"product_exp\">{{product_exp}}</td>  \r\n");
      out.write("\t\t\t<td class=\"img\"><img src=/img/product/{{img}} width=50></td>  \r\n");
      out.write("\t\t\t<td><button>발주하기</button></td>  \r\n");
      out.write("           </tr>      \r\n");
      out.write("           {{/each}}\r\n");
      out.write("      </script>\r\n");
      out.write("      \t\t<input type=\"button\" id=\"btnSelect\" value=\"선택발주\">\r\n");
      out.write("            <div id=\"pagination\">\r\n");
      out.write("         <button id=\"btnPre\">◀</button>\r\n");
      out.write("         <button id=\"btnNext\">▶</button>\r\n");
      out.write("         [<span id=\"curPage\"></span>/<span id=\"totPage\"></span>]\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar url=\"/semi/product/list\";\r\n");
      out.write("\t\r\n");
      out.write("\t//선택발주 버튼을 눌렀을때\r\n");
      out.write("\t$(\"#btnSelect\").on(\"click\", function(){\r\n");
      out.write("\t\tif(!confirm(\"발주하시겠습니까?\")) return;\r\n");
      out.write("\t\tif($(\"#tbl .row .chk:checked\").length > 0) {\r\n");
      out.write("\t\t\t$(\"#tbl .row .chk:checked\").each(function(){\r\n");
      out.write("\t\t\t\tvar row=$(this).parent().parent();\r\n");
      out.write("\t\t\t\tvar category_code=row.find(\".product_code\").html().substring(0,1);\r\n");
      out.write("\t\t\t\tvar product_code=row.find(\".product_code\").html().substring(1);\r\n");
      out.write("\t\t\t\tvar category_name=row.find(\".category_name\").html();\r\n");
      out.write("\t\t\t\tvar product_name=row.find(\".product_name\").html();\r\n");
      out.write("\t\t\t\tvar product_price=row.find(\".product_price\").html();\r\n");
      out.write("\t\t\t\tvar company=row.find(\".company\").html()\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\t\turl:\"/semi/cart/insert\",\r\n");
      out.write("\t\t\t\t\tdata:{\"category_code\":category_code, \"product_code\":product_code, \"product_name\":product_name,\r\n");
      out.write("\t\t\t\t\t\t\"product_price\":product_price, \"company\":company, \"category_name\":category_name},\r\n");
      out.write("\t\t\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\t\t\talert(\"발주되었습니다.\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(\"unable\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//발주버튼 눌렀을떄\r\n");
      out.write("\t$(\"#tbl\").on(\"click\",\".row button\",function(){\r\n");
      out.write("\t\tif(!confirm(\"발주ㄱ?\")) return;\r\n");
      out.write("\t\tvar row=$(this).parent().parent();\r\n");
      out.write("\t\tvar category_code=row.find(\".product_code\").html().substring(0,1);\r\n");
      out.write("\t\tvar product_code=row.find(\".product_code\").html().substring(1);\r\n");
      out.write("\t\tvar category_name=row.find(\".category_name\").html();\r\n");
      out.write("\t\tvar product_name=row.find(\".product_name\").html();\r\n");
      out.write("\t\tvar product_price=row.find(\".product_price\").html();\r\n");
      out.write("\t\tvar company=row.find(\".company\").html()\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"/semi/cart/insert\",\r\n");
      out.write("\t\t\tdata:{\"category_code\":category_code, \"product_code\":product_code, \"product_name\":product_name,\r\n");
      out.write("\t\t\t\t\"product_price\":product_price, \"company\":company, \"category_name\":category_name},\r\n");
      out.write("\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\talert(\"발주되었습니다.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//전체체크버튼을 눌렀을때\r\n");
      out.write("\t$(\"#tbl\").on(\"click\", \"#chkAll\", function() {\r\n");
      out.write("\t\tif ($(this).is(\":checked\")) {\r\n");
      out.write("\t\t\t$(\"#tbl .row .chk\").each(function() {\r\n");
      out.write("\t\t\t\t$(this).prop(\"checked\", true);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$(\"#tbl .row .chk\").each(function() {\r\n");
      out.write("\t\t\t\t$(this).prop(\"checked\", false);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t//각행의 체크버튼을 클릭한 경우\r\n");
      out.write("\t$(\"#tbl\").on(\"click\", \".row .chk\", function() {\r\n");
      out.write("\t\tvar isChkAll = true;\r\n");
      out.write("\t\t$(\"#tbl .row .chk\").each(function() {\r\n");
      out.write("\t\t\tif (!$(this).is(\":checked\"))\r\n");
      out.write("\t\t\t\tisChkAll = false;\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tif (isChkAll) {\r\n");
      out.write("\t\t\t$(\"#tbl #chkAll\").prop(\"checked\", true);\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$(\"#tbl #chkAll\").prop(\"checked\", false);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"../home.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
