/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-06-17 09:21:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.record;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class record3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>히히호호</title>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("#tbl1, #tbl2, #tbl3 {\r\n");
      out.write("\twidth: 1000px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".help {width:1000px; margin:auto; float:center; text-align:center;}\r\n");
      out.write("\r\n");
      out.write("h2 {text-align:center;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"divPage\">\r\n");
      out.write("\t\t<div id=\"divMenu\"></div>\r\n");
      out.write("\t\t<div id=\"divHeader\">\r\n");
      out.write("\t\t\t<h2>인 기 상 품 목 록</h2>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"haha\">\r\n");
      out.write("\t\t\t<div class=\"help\">\r\n");
      out.write("\t\t\t\t<h2>1월 인기상품</h2>\r\n");
      out.write("\t\t\t\t<div id=\"tbl1\"></div>\r\n");
      out.write("\t\t\t\t<script id=\"temp1\" type=\"text/x-handlebars-template\">  \r\n");
      out.write("         {{#each array}}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"image\"><img src=\"{{printImage image}}\"><br>\r\n");
      out.write("\t\t\t\t\t상품명 : {{product_name}}<br>판매수량 : {{sold_quantity}}</div>\r\n");
      out.write("\t\t\t{{/each}}\t\t\r\n");
      out.write("      </script>\r\n");
      out.write("\t\t\t</div><br>\r\n");
      out.write("\t\t\t<div class=\"help\">\r\n");
      out.write("\t\t\t\t<h2>2월 인기상품</h2>\r\n");
      out.write("\t\t\t\t<div id=\"tbl2\"></div>\r\n");
      out.write("\t\t\t\t<script id=\"temp2\" type=\"text/x-handlebars-template\">       \r\n");
      out.write("         {{#each array}}       \r\n");
      out.write("\t\t\t\t\t<div class=\"image\"><img src=\"{{printImage image}}\"><br>\r\n");
      out.write("\t\t\t\t\t상품명 : {{product_name}}<br> 판매수량 : {{sold_quantity}}</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("           {{/each}}\r\n");
      out.write("      </script>\r\n");
      out.write("      \r\n");
      out.write("\t\t\t</div><br>\r\n");
      out.write("\t\t\t<div class=\"help\">\r\n");
      out.write("\t\t\t\t<h2>3월 인기상품</h2>\r\n");
      out.write("\t\t\t\t<div id=\"tbl3\"></div>\r\n");
      out.write("\t\t\t\t<script id=\"temp3\" type=\"text/x-handlebars-template\">        \r\n");
      out.write("         {{#each array}}       \r\n");
      out.write("        \t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"image\"><img src=\"{{printImage image}}\"><br>\r\n");
      out.write("\t\t\t\t\t상품명 : {{product_name}}<br>판매수량 : {{sold_quantity}}</div>\r\n");
      out.write("\t\t\t\t   \r\n");
      out.write("           {{/each}}\r\n");
      out.write("      </script>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar selMonth;\r\n");
      out.write("\r\n");
      out.write("\tgetList(1);\r\n");
      out.write("\tgetList(2);\r\n");
      out.write("\tgetList(3);\r\n");
      out.write("\r\n");
      out.write("\tfunction getList(selMonth) {\r\n");
      out.write("\r\n");
      out.write("\t\t$\r\n");
      out.write("\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\t\turl : \"/semi/record/topTen\",\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\"selMonth\" : selMonth\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tvar template = Handlebars.compile($(\"#temp\" + selMonth)\r\n");
      out.write("\t\t\t\t\t\t\t\t.html());\r\n");
      out.write("\t\t\t\t\t\t$(\"#tbl\" + selMonth).html(template(data));\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tHandlebars.registerHelper(\"printImage\", function(image) {\r\n");
      out.write("\t\tvar src;\r\n");
      out.write("\t\tif (!image)\r\n");
      out.write("\t\t\tsrc = \"http://placehold.it/200x300\";\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\tsrc = \"/img/product/\" + image;\r\n");
      out.write("\t\treturn src;\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
