/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-06-17 08:38:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.record;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class record2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>히히호호</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div id=\"divPage\">\r\n");
      out.write("      <div id=\"divMenu\"></div>\r\n");
      out.write("      <div id=\"divHeader\">\r\n");
      out.write("         <h2>상 품 목 록</h2>\r\n");
      out.write("      </div>\r\n");
      out.write("       <h2>1월 인기상품</h2>\r\n");
      out.write("       <table id=\"tbl1\" border=1></table>    \r\n");
      out.write("         <script id=\"temp1\" type=\"text/x-handlebars-template\">  \r\n");
      out.write("          <tr class=\"title\">   \r\n");
      out.write("\t\t\t<td width=130>이미지</td> \r\n");
      out.write("            <td width=130>상품명</td> \r\n");
      out.write("            <td width=130>판매수량</td>\r\n");
      out.write("          </tr>       \r\n");
      out.write("         {{#each array}}       \r\n");
      out.write("          <tr class=\"row\">\r\n");
      out.write("\t\t\t<td><img src=\"{{printImage image}}\"></td>\r\n");
      out.write("\t\t\t<td class=\"product\">{{product_name}}</td>                \r\n");
      out.write("            <td class=\"quantity\">{{sold_quantity}}</td>    \r\n");
      out.write("           </tr>      \r\n");
      out.write("           {{/each}}\r\n");
      out.write("      </script>\r\n");
      out.write("       <h2>2월 인기상품</h2>\r\n");
      out.write("      <table id=\"tbl2\" border=1></table>    \r\n");
      out.write("         <script id=\"temp2\" type=\"text/x-handlebars-template\">  \r\n");
      out.write("          <tr class=\"title\">    \r\n");
      out.write("\t\t\t<td width=130>이미지</td>\r\n");
      out.write("            <td width=130>상품명</td> \r\n");
      out.write("            <td width=130>판매수량</td>\r\n");
      out.write("          </tr>       \r\n");
      out.write("         {{#each array}}       \r\n");
      out.write("          <tr class=\"row\">\r\n");
      out.write("\t\t\t<td><img src=\"{{printImage image}}\"></td>\r\n");
      out.write("\t\t\t<td class=\"product\">{{product_name}}</td>                \r\n");
      out.write("            <td class=\"quantity\">{{sold_quantity}}</td>    \r\n");
      out.write("           </tr>      \r\n");
      out.write("           {{/each}}\r\n");
      out.write("      </script>\r\n");
      out.write("      \r\n");
      out.write("      <h2>3월 인기상품</h2>\r\n");
      out.write("      <table id=\"tbl3\" border=1></table>    \r\n");
      out.write("         <script id=\"temp3\" type=\"text/x-handlebars-template\">  \r\n");
      out.write("          <tr class=\"title\">    \r\n");
      out.write("\t\t\t<td width=130>이미지</td>\r\n");
      out.write("            <td width=130>상품명</td> \r\n");
      out.write("            <td width=130>판매수량</td>\r\n");
      out.write("          </tr>       \r\n");
      out.write("         {{#each array}}       \r\n");
      out.write("          <tr class=\"row\">\r\n");
      out.write("\t\t\t<td><img src=\"{{printImage image}}\"></td>\r\n");
      out.write("\t\t\t<td class=\"product\">{{product_name}}</td>                \r\n");
      out.write("            <td class=\"quantity\">{{sold_quantity}}</td>    \r\n");
      out.write("           </tr>      \r\n");
      out.write("           {{/each}}\r\n");
      out.write("      </script>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar selMonth;\r\n");
      out.write("\t\r\n");
      out.write("\tgetList(1);\r\n");
      out.write("\tgetList(2);\r\n");
      out.write("\tgetList(3);\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getList(selMonth){     \r\n");
      out.write("\t\r\n");
      out.write("    $.ajax({           \r\n");
      out.write("       type:\"get\",       \r\n");
      out.write("       url:\"/semi/record/topTen\",    \r\n");
      out.write("       data:{\"selMonth\":selMonth},     \r\n");
      out.write("       dataType:\"json\",   \r\n");
      out.write("       success:function(data){  \r\n");
      out.write("     \t  \r\n");
      out.write("          var template = Handlebars.compile($(\"#temp\"+selMonth).html());        \r\n");
      out.write("          $(\"#tbl\"+selMonth).html(template(data));\r\n");
      out.write("       }\r\n");
      out.write("       }); \r\n");
      out.write("    } \r\n");
      out.write("\t\r\n");
      out.write("\t Handlebars.registerHelper(\"printImage\", function(image){         \r\n");
      out.write("\t\t var src;      \r\n");
      out.write("\t\t if(!image) src=\"http://placehold.it/100x60\"; else src=\"/img/product/\" + image; return src;  \r\n");
      out.write("\t\t });\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
