/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-06-10 06:11:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mall;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class listAll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>Insert title here</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t#tbl {width:350px; margin: auto;}\r\n");
      out.write("\t\t#pagination, h2 {width: 350px;margin: auto;text-align: center;margin-top: 10px;margin-bottom: 10px;}\r\n");
      out.write("\t\ttable {border-collapse: collapse;}\r\n");
      out.write("\t\ttd {border: 1px solid black;height: 30px;font-size: 12px;padding: 0px 5px 0px 5px;}\r\n");
      out.write("\t\ttable .title {background: #EAEAEA;text-align: center;}\r\n");
      out.write("\t\ttable .row:hover {background: gray;color: white;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"divAll\">\r\n");
      out.write("\t\t<h2>업 체 목 록</h2>\r\n");
      out.write("\t\t<input id=\"selPerPage\" type=\"hidden\" value=3>\r\n");
      out.write("\t\t<table id=\"tbl\"></table>\r\n");
      out.write("\t\t<script id=\"temp\" type=\"text/x-handlebars-template\">  \r\n");
      out.write("        <tr class=\"title\">\r\n");
      out.write("\t\t\t<td width=100>업체코드</td>\r\n");
      out.write("\t\t\t<td width=100>업체명</td>\r\n");
      out.write("\t\t\t<td width=150>전화번호</td>\r\n");
      out.write("\t\t</tr>       \r\n");
      out.write(" \t\t{{#each array}}    \r\n");
      out.write("    \t<tr class=\"row\">\r\n");
      out.write("            <td class=\"mall_id\">{{mall_id}}</td>    \r\n");
      out.write("        \t<td class=\"mall_name\">{{mall_name}}</td>   \r\n");
      out.write("         \t<td>{{tel}}</td>     \r\n");
      out.write("   \t\t</tr>    \r\n");
      out.write("    \t{{/each}}\r\n");
      out.write("    </script>\r\n");
      out.write("\t\t<div id=\"pagination\">\r\n");
      out.write("\t\t\t<button id=\"btnPre\">◀</button>\r\n");
      out.write("\t\t\t<button id=\"btnNext\">▶</button>\r\n");
      out.write("\t\t\t[<span id=\"curPage\"></span>/<span id=\"totPage\"></span>]\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("var url=\"list\";   \r\n");
      out.write("$(\"#tbl\").on(\"click\", \".row\", function(){  \r\n");
      out.write("\tvar mall_id=$(this).find(\".mall_id\").html();    \r\n");
      out.write("\tvar mall_name=$(this).find(\".mall_name\").html();  \r\n");
      out.write("\t$(opener.frm.mall_id).val(mall_id);   \r\n");
      out.write("\t$(opener.frm.mall_name).val(mall_name);   \r\n");
      out.write("\twindow.close();  \r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"../home.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
