/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-06-12 02:40:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class blogList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>블로그 검색</title>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"user-scalable=no, width=device-width\" charset=\"euc-kr\"/>\r\n");
      out.write("    <link href=\"home_mobile.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen and (max-width:799px)\">\r\n");
      out.write("    <link href=\"home.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen and (min-width:800px)\">\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"divPage\">\r\n");
      out.write("\t<div id=\"divMenu\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("</div>\r\n");
      out.write("\t<div id=\"divHeader\">\r\n");
      out.write("\t\t\t<h2>블로그 검색</h2>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<div id=\"divCondition\">\r\n");
      out.write("\t\t<input type=\"text\" id=\"query\" value=\"자바\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"검색\" id=\"btnSearch\">\r\n");
      out.write("\t\t<select id=\"display\">\r\n");
      out.write("\t\t\t<option value=\"5\">5행</option>\r\n");
      out.write("\t\t\t<option value=\"10\">10행</option>\r\n");
      out.write("\t\t\t<option value=\"15\">15행</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<span id=\"total\"></span>\r\n");
      out.write("\t\t<table id=\"tbl\" border=1></table>\r\n");
      out.write("\t\t<script id=\"temp\" type=\"text/x-handlebars-template\"> \r\n");
      out.write("\t\t\t<tr class=\"title\">\r\n");
      out.write("\t\t\t\t<td>제목</td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t{{#each items}}\r\n");
      out.write("\t\t\t<tr class=\"row\">\r\n");
      out.write("\t\t\t\t<td><a href=\"{{link}}\">{{{title}}}</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t{{/each}}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<div id=\"pagination\">\r\n");
      out.write("\t\t\t<button id=\"btnPre\">◀</button>\r\n");
      out.write("\t\t\t<button id=\"btnNext\">▶</button>\r\n");
      out.write("\t\t\t[<span id=\"curPage\"></span>/<span id=\"totPage\"></span>]\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var url=\"/API/naver/blog\";\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"home.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
