/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-06-12 07:08:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class localList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>장소 검색</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"home.css\">\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=2d06e7f6c04a5b6cff4d94cebfef1694\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"divPage\">\r\n");
      out.write("\t<div id=\"divMenu\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("</div>\r\n");
      out.write("\t<div id=\"divHeader\">\r\n");
      out.write("\t\t\t<h2>장소 검색</h2>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<div id=\"divCondition\">\r\n");
      out.write("\t\t<input type=\"text\" id=\"query\" value=\"자바\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"검색\" id=\"btnSearch\">\r\n");
      out.write("\t\t<select id=\"size\">\r\n");
      out.write("\t\t\t<option value=\"5\">5행</option>\r\n");
      out.write("\t\t\t<option value=\"10\">10행</option>\r\n");
      out.write("\t\t\t<option value=\"15\">15행</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<span id=\"total\"></span>건\r\n");
      out.write("\t\t<table id=\"tbl\" border=1></table>\r\n");
      out.write("\t\t<script id=\"temp\" type=\"text/x-handlebars-template\"> \r\n");
      out.write("\t\t\t<tr class=\"title\">\r\n");
      out.write("\t\t\t\t<td width=200>장소이름</td>\t\r\n");
      out.write("\t\t\t\t<td width=300>도로명주소</td>\r\n");
      out.write("\t\t\t\t<td width=130>전화번호</td>\r\n");
      out.write("\t\t\t\t<td\twidth=70>지도보기</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t{{#each documents}}\r\n");
      out.write("\t\t\t<tr class=\"row\">\r\n");
      out.write("\t\t\t\t<td><a href=\"{{place_url}}\">{{place_name}}</a></td>\r\n");
      out.write("\t\t\t\t<td>{{road_address_name}}</td>\r\n");
      out.write("\t\t\t\t<td>{{phone}}</td>\r\n");
      out.write("\t\t\t\t<td><button x=\"{{x}}\" y=\"{{y}}\" place=\"{{place_name}}\" phone=\"{{phone}}\" address=\"{{road_address_name}}\">지도보기</button></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t{{/each}}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"pagination\">\r\n");
      out.write("\t\t<button id=\"btnPre\">◀</button>\r\n");
      out.write("\t\t<button id=\"btnNext\">▶</button>\r\n");
      out.write("\t\t[<span id=\"curPage\"></span>/<span id=\"totPage\"></span>]\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"map\" style=\"width:800px;height:400px;float:center;margin:auto;\"></div><br>\r\n");
      out.write("\t<div id=\"btnClose\" style=\"float:center;margin:auto;text-align:center;\"><input type=\"button\" value=\"지도끄기\" id=\"button\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\tvar page=1, size, query, total, totpage,x,y;\r\n");
      out.write("\r\n");
      out.write("\t$(\"#map\").hide();\r\n");
      out.write("\t$(\"#btnClose\").hide();\r\n");
      out.write("\tgetList();\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btnClose #button\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#map\").hide();\r\n");
      out.write("\t\t$(\"#btnClose\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#tbl\").on(\"click\", \".row button\", function(){\r\n");
      out.write("\t\tx=$(this).attr(\"x\");\r\n");
      out.write("\t\ty=$(this).attr(\"y\");\r\n");
      out.write("\t\tvar place=$(this).attr(\"place\");\r\n");
      out.write("\t\tvar phone=$(this).attr(\"phone\");\r\n");
      out.write("\t\tvar address=$(this).attr(\"address\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#map\").show();\r\n");
      out.write("\t\t$(\"#btnClose\").show();\r\n");
      out.write("\t\tvar container = document.getElementById('map');\r\n");
      out.write("\t\tvar options = {\r\n");
      out.write("\t\t\tcenter: new kakao.maps.LatLng(y, x),\r\n");
      out.write("\t\t\tlevel: 3\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tvar marker=new kakao.maps.Marker({position:new kakao.maps.LatLng(y,x)});\r\n");
      out.write("\t\tvar map = new kakao.maps.Map(container, options);\r\n");
      out.write("\t\tmarker.setMap(map);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar str=\"<div style='background:white; color:black; box-shadow:10px 10px 10px black;border:5px solid black; border-radius:5px;'>\" + place + \"<br>\" + phone + \"<br>\"+ address +\"</div>\";\r\n");
      out.write("\t       var info=new kakao.maps.InfoWindow({content:str});\r\n");
      out.write("\t       kakao.maps.event.addListener(marker, \"mouseover\", function(){ info.open(map, marker); });\r\n");
      out.write("\t       kakao.maps.event.addListener(marker, \"mouseout\", function(){ info.close(map, marker); });      \r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btnNext\").click(function() {\r\n");
      out.write("\t\tpage++;\r\n");
      out.write("\t\tgetList();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#btnPre\").click(function() {\r\n");
      out.write("\t\tpage--;\r\n");
      out.write("\t\tgetList();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#size, #query\").change(function(){\r\n");
      out.write("\t\tpage=1;\r\n");
      out.write("\t\tgetList();\r\n");
      out.write("\t});\r\n");
      out.write("\t/*\r\n");
      out.write("\t$(\"#display, #query\").on(\"change\",function(){\r\n");
      out.write("\t\tpage=1;\r\n");
      out.write("\t\tgetList();\r\n");
      out.write("\t});\r\n");
      out.write("\t*/\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#query\").keydown(function(key) {\r\n");
      out.write("\t\t  if(key.keycode==13) {\r\n");
      out.write("\t\t\t  page=1;\r\n");
      out.write("\t\t\t  getList();\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t  });\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btnSearch\").on(\"click\", function(){\r\n");
      out.write("\t\tpage=1;\r\n");
      out.write("\t\tgetList();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getList(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tquery=$(\"#query\").val();\r\n");
      out.write("\t\tsize=$(\"#size\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"get\",\r\n");
      out.write("\t\turl:\"https://dapi.kakao.com/v2/local/search/keyword.json\",\r\n");
      out.write("\t\theaders:{\"Authorization\":\"KakaoAK 2d06e7f6c04a5b6cff4d94cebfef1694\"},\r\n");
      out.write("\t\tdataType:\"json\",\r\n");
      out.write("\t\tdata:{\"query\": query, \"page\": page, \"size\":size},\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tvar template = Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("            $(\"#tbl\").html(template(data));\r\n");
      out.write("            \r\n");
      out.write("            total=data.meta.pageable_count;\r\n");
      out.write("            if(total%size==0){\r\n");
      out.write("               totPage=total/size;\r\n");
      out.write("            }else{\r\n");
      out.write("               totPage=parseInt(total/size)+1;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            if (page == 1)\r\n");
      out.write("\t\t\t\t$(\"#btnPre\").attr(\"disabled\", true);// 현재 페이지가 1페이지인 경우\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\t$(\"#btnPre\").attr(\"disabled\", false);\r\n");
      out.write("\t\t\tif (data.meta.is_end) // 현재 페이지가 마지막 페이지인 경우\r\n");
      out.write("\t\t\t\t$(\"#btnNext\").attr(\"disabled\", true);\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\t$(\"#btnNext\").attr(\"disabled\", false);\r\n");
      out.write("\t\t\t\r\n");
      out.write("            total=data.meta.pageable_count;\r\n");
      out.write("            $(\"#curPage\").html(page);\r\n");
      out.write("            $(\"#totPage\").html(totPage);\r\n");
      out.write("            $(\"#total\").html(total);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
