/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-06-23 04:43:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bbs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../home.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../enter.css\" media=\"all\" />\r\n");
      out.write("<title>이거어때</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div id=divPage>\r\n");
      out.write("   <div id=\"divTop\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../top2.jsp", out, false);
      out.write("</div>\r\n");
      out.write("\t\t<div class=\"dropmenu\">\r\n");
      out.write("\t\t\t<ul id=\"dm_ul\" style=\"background:white\">\r\n");
      out.write("\t\t\t\t<li><a id=plist href=\"/semiProject/product/list.jsp\">상품리스트</a></li>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li>현황관리\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=alist href=\"/semiProject/stock/list.jsp\">재고현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=alist href=\"/semiProject/sell_status/list.jsp\">판매현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=alist href=\"/semiProject/order/list.jsp\">발주현황</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<li>등록관리\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=alist href=\"/semiProject/cart/cartList.jsp\">발주등록</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=alist href=\"/semiProject/product/insert.jsp\">상품등록</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<li><a href=\"/semiProject/bbs/list.jsp\" style=text-decoration:none;color:#2569C9>이거어때?</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=alist href=\"/semiProject/bbs/insert.jsp\">제안해요</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("     <div id=header></div>\r\n");
      out.write("      <div id=center>\r\n");
      out.write("         <div id=menu>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../menu.jsp", out, false);
      out.write("</div>\r\n");
      out.write("         <!-- contents -->\r\n");
      out.write("         <div id=\"contents\" style=\"margin: auto;\">\r\n");
      out.write("         \t<br><br>\t<br><br>\r\n");
      out.write("            <ul id=\"holder\" class=\"txtControll\">\r\n");
      out.write("            </ul>\r\n");
      out.write("            <h1 style=margin-bottom:35px;text-align:center>이거어때?</h1>\r\n");
      out.write("            <div class=\"relCon\">\r\n");
      out.write("               <!-- 아이디어 작성하기 -->\r\n");
      out.write("               <div class=\"proposal idea\">\r\n");
      out.write("                  <div class=\"info_comment\">\r\n");
      out.write("                     <dl>\r\n");
      out.write("                        <dt>알려드립니다.</dt>\r\n");
      out.write("                        <dd>\r\n");
      out.write("                           <ul>\r\n");
      out.write("                              <li>단순 불만 사항, 장난성 글, 욕설 및 비방, 광고글, 반복 게시물 등은 예고 없이 삭제될 수\r\n");
      out.write("                                 있습니다.</li>\r\n");
      out.write("                              <li>게시판 성격에 맞지 않는 글은 임의로 이동되거나 삭제될 수 있습니다.</li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                        </dd>\r\n");
      out.write("                     </dl>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"staffTit mb20\">\r\n");
      out.write("                     <h3 class=\"fl\">기본 입력 항목</h3>\r\n");
      out.write("                     <p class=\"fr\" style=\"width: 785px; float: right;\">\r\n");
      out.write("                    \r\n");
      out.write("                     </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"table04 mb40\">\r\n");
      out.write("                     <form name=\"frm\" action=\"insert\" method=\"post\" style=height:300px;>\r\n");
      out.write("                        <table id=tbl  \r\n");
      out.write("                          style=\"table-layout: fixed;\">\r\n");
      out.write("                           <colgroup>\r\n");
      out.write("                              <col width=\"140\">\r\n");
      out.write("                              <col width=\"*\">\r\n");
      out.write("                           </colgroup>\r\n");
      out.write("                           <tbody>\r\n");
      out.write("                              <tr>\r\n");
      out.write("                                 <th><span>제목</span><img src=\"check.png\" alt=\"필수 입력 사항\"\r\n");
      out.write("                                    class=\"essential\"></th>\r\n");
      out.write("                                 <td><label for=\"title\"><input type=\"text\"\r\n");
      out.write("                                       name=\"title\" class=\"input_text\" id=\"title\"\r\n");
      out.write("                                       style=\"width: 785px;\" placeholder=\"제목은 40자 이내로 작성해주세요.\" /></label></td>\r\n");
      out.write("                              </tr>\r\n");
      out.write("                              <tr>\r\n");
      out.write("                                 <th><span>내용</span><img src=\"check.png\" alt=\"필수 입력 사항\"\r\n");
      out.write("                                    class=\"essential\"></th>\r\n");
      out.write("                                 <td class=\"contentsTxt\"><textarea name=\"contents\"\r\n");
      out.write("                                       class=\"textarea\" style=\"width: 795px;\" id=\"content\"\r\n");
      out.write("                                       value=\"내용을 입력하세요\"></textarea></td>\r\n");
      out.write("                              </tr>\r\n");
      out.write("                           </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <input type=button id=\"golist\" value=\"목록\" style= \"background-color: #2569C9;\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 5px 12px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  margin: 4px 2px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  border-radius:10px;\">\r\n");
      out.write("                        <input type=submit\r\n");
      out.write("                           value=\"아이디어 작성 완료\" style= \"background-color: #2569C9;\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 5px 12px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  margin: 4px 2px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  border-radius:10px;\"> <input type=reset value=\"취소\" style= \"background-color: #2569C9;\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 5px 12px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  margin: 4px 2px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  border-radius:10px;\">\r\n");
      out.write("                     </form>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!--// 아이디어 작성하기 -->\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--// contents -->\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"divFoot\" style=\"text-align: center\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("</div>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(\".dropmenu ul li\").hover(function(){\r\n");
      out.write("\t$(this).find(\"ul\").stop().fadeToggle(300);\r\n");
      out.write("})\r\n");
      out.write("\t//목록으로 이동\r\n");
      out.write("\t$(\"#golist\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href=\"/semiProject/bbs/list.jsp\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("   //값이 들어가있는지 체크하는 식\r\n");
      out.write("   $(frm).submit(function(e) {\r\n");
      out.write("      e.preventDefault(); //서브밋 방지\r\n");
      out.write("      if (!confirm(\"저장하시겠습니까?\"))\r\n");
      out.write("         return;\r\n");
      out.write("\r\n");
      out.write("      var title = $(frm.title).val();\r\n");
      out.write("      var contents = $(frm.contents).val();\r\n");
      out.write("\r\n");
      out.write("      alert(title + contents);\r\n");
      out.write("\r\n");
      out.write("      if (title == \"\") {\r\n");
      out.write("         alert(\"제목을 입력하세요!\");\r\n");
      out.write("         $(frm.title).focus();\r\n");
      out.write("      } else if (contents == \"\") {\r\n");
      out.write("         alert(\"내용을 입력하세요!\");\r\n");
      out.write("         $(frm.contents).focus();\r\n");
      out.write("      } else {\r\n");
      out.write("         frm.submit();\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
