/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-06-23 04:43:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bbs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class read_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1589249480000L));
    _jspx_dependants.put("jar:file:/C:/data/jsp/jsp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/semiProject/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/C:/data/jsp/jsp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/semiProject/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/C:/data/jsp/jsp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/semiProject/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("\t<title>편의점 관리시스템</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../enter.css\" media=\"all\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../home.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"divPage\">\r\n");
      out.write("\t<div id=\"divTop\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../top2.jsp", out, false);
      out.write("</div>\r\n");
      out.write("\t<div class=\"dropmenu\">\r\n");
      out.write("\t\t\t<ul id=\"dm_ul\" style=\"background: white; margin-bottom: 20px\">\r\n");
      out.write("\t\t\t\t<li><a id=plist href=\"/semiProject/product/list.jsp\">상품리스트</a></li>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li>현황관리\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=alist href=\"/semiProject/stock/list.jsp\">재고현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=alist href=\"/semiProject/sell_status/list.jsp\">판매현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=alist href=\"/semiProject/order/list.jsp\">발주현황</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<li>등록관리\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=alist href=\"/semiProject/cart/cartList.jsp\">발주등록</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=alist href=\"/semiProject/product/insert.jsp\">상품등록</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<li>이건어때\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=alist href=\"/semiProject/bbs/insert.jsp\">제안해요</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div class=\"relCon\">\r\n");
      out.write("\t\t<!-- 아이디어 게시판-view -->\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<div class=\"idea_list\">\r\n");
      out.write("\t\t\t<!-- view영역 -->\r\n");
      out.write("\t\t\t<!-- 2018-01-12이거어때 -->\r\n");
      out.write("\t\t\t<div class=\"idea_view\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"cont_box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"head_cont\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"etc\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><strong class=\"tit\">등록일</strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"detail_box\">\r\n");
      out.write("\t\t\t\t\t<!-- 2018-04-04 추가 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"txt_detail\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.contents}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"table03 mb20\" style=float:right;>\r\n");
      out.write("\t\t\t\t<table summary=\"상세목록\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n");
      out.write("\t\t\t\t\tstyle=\"table-layout: fixed;\">\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col width=\"120\">\r\n");
      out.write("\t\t\t\t\t\t<col width=\"*\">\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<tbody >\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" id=\"preRead\" value=\"이전글\" style= \"background-color: #2569C9;\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 5px 12px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  margin: 4px 2px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  border-radius:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" id=\"nextRead\" value=\"다음글\"style= \"background-color: #2569C9;\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 5px 12px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  margin: 4px 2px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  border-radius:10px;\">\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--// 이전글, 다음글 -->\r\n");
      out.write("\t\t\t<div class=\"btnNormal\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<button id=\"bbsupdate\"style= \"background-color: #2569C9;\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 5px 12px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  margin: 4px 2px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  border-radius:10px;\">수정</button>\r\n");
      out.write("  \r\n");
      out.write("\t\t\t\t<button id=\"bbsdelete\"style= \"background-color: #2569C9;\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 5px 12px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  margin: 4px 2px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  border-radius:10px;\">삭제</button>\r\n");
      out.write("  <a href=\"list.jsp\" ><button id=\"bbsdelete\"style= \"background-color: #2569C9;\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 5px 12px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  margin: 4px 2px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  border-radius:10px;\">목록</button></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"prodSnsReply\" id=\"ideaTable\">\r\n");
      out.write("\t\t\t\t<div class=\"reply_box_n_wrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"reply_box_n\">\r\n");
      out.write("\t\t\t\t\t\t<textarea name=\"rplContent\" id=\"rplContent\" cols=\"30\" rows=\"10\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width:943px;\" placeholder=\"게시판 성격과 무관한 댓글, 악플은 삭제될 수 있습니다.\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn_reply\" style=\"cursor:pointer;\">댓글달기</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<ul class=\"idea_add\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<strong>아이디어에 당신의 아이디어를 추가해 보세요.</strong><!-- 아이디어 댓글 없을 때 -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div id=\"tbl\"></div>\r\n");
      out.write("\t\t\t\t\t<script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t\t\t\t{{#each bArray}}\r\n");
      out.write("\t\t\t\t\t\t<div class=\"balloon_new\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"info_area\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"idea_photo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"../images/leftbro.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"mask\"></span> <!-- 이미지 동그라미 마스크 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"snsId\">(익명)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"etc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn_del\" style=\"cursor:pointer;\">삭제</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"bno\" value=\"{{bno}}\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"rno\" value=\"{{rno}}\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"snsContents\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t{{contents}}\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"snsdate\">{{date}}</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<strong id=\"likeStr325\">{{ulike}}</strong>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t{{/each}}\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"divFoot\" style=\"text-align: center\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("$(\".dropmenu ul li\").hover(function() {\r\n");
      out.write("\t$(this).find(\"ul\").stop().fadeToggle(300);\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("var bno=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("var maxbno=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("getList();\r\n");
      out.write("\r\n");
      out.write("//댓글삭제\r\n");
      out.write("$(\"#tbl\").on(\"click\",\".btn_del\",function(){\r\n");
      out.write("  if(!confirm(\"댓글을 삭제하시겠습니까?\")) return;\r\n");
      out.write("  var rno=$(\"#rno\").val();\r\n");
      out.write("  $.ajax({\r\n");
      out.write("     type:\"post\",\r\n");
      out.write("     url:\"replydelete\",\r\n");
      out.write("     data:{\"bno\":bno,\"rno\":rno},\r\n");
      out.write("     success:function(){\r\n");
      out.write("           alert(\"삭제되었습니다!\");\r\n");
      out.write("           getList();\r\n");
      out.write("     }\r\n");
      out.write("  });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//댓글등록\r\n");
      out.write("$(\".reply_box_n\").on(\"click\",\".btn_reply\",function(){\r\n");
      out.write("\tvar contents=$(\"#rplContent\").val();\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"post\",\r\n");
      out.write("\t\turl:\"replyinsert\",\r\n");
      out.write("\t\tdata:{\"bno\":bno,\"contents\":contents},\r\n");
      out.write("\t\tsuccess:function(){\r\n");
      out.write("\t\t\tgetList();\r\n");
      out.write("\t\t\tlocation.href=\"/semiProject/bbs/read?bno=\"+bno;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function getList(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"get\",\r\n");
      out.write("\t\turl:\"replylist\",\r\n");
      out.write("\t\tdata:{\"bno\":bno},\r\n");
      out.write("\t\tdataType:\"json\",\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tvar template = Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("\t\t\t$(\"#tbl\").html(template(data));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//게시글삭제\r\n");
      out.write("$(\"#bbsdelete\").on(\"click\",function(){\r\n");
      out.write("  if(!confirm(\"삭제하시겠습니까?\")) return;\r\n");
      out.write("  var company_id=$(\"#idididid\").val();\r\n");
      out.write("  $.ajax({\r\n");
      out.write("     type:\"post\",\r\n");
      out.write("     url:\"delete\",\r\n");
      out.write("     dataType:\"json\",\r\n");
      out.write("     data:{\"company_id\":company_id,\"bno\":bno},\r\n");
      out.write("     success:function(data){\r\n");
      out.write("        if(data.count==1){\r\n");
      out.write("           alert(\"삭제되었습니다!\");\r\n");
      out.write("           location.href=\"/semiProject/bbs/list.jsp\";\r\n");
      out.write("        }else{\r\n");
      out.write("           alert(\"권한이 없습니다!\");\r\n");
      out.write("        }\r\n");
      out.write("     }\r\n");
      out.write("  });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//수정으로 이동\r\n");
      out.write("$(\"#bbsupdate\").on(\"click\",function(){\r\n");
      out.write("  location.href=\"/semiProject/bbs/update?bno=\"+bno;\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#preRead\").on(\"click\",function(){\r\n");
      out.write("  var prebno=bno-1;\r\n");
      out.write("  var prebno=parseInt(bno) - 1;\r\n");
      out.write("  location.href=\"/semiProject/bbs/read?bno=\"+prebno;\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("if(bno==1){\r\n");
      out.write("  $(\"#preRead\").attr(\"disabled\",true);\r\n");
      out.write("};\r\n");
      out.write("if(bno==maxbno){\r\n");
      out.write("  $(\"#nextRead\").attr(\"disabled\",true)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(\"#nextRead\").on(\"click\",function(){\r\n");
      out.write("  var prebno=bno+1;\r\n");
      out.write("  var prebno=parseInt(bno) + 1;\r\n");
      out.write("  location.href=\"/semiProject/bbs/read?bno=\"+prebno;\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
