/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-06-03 07:05:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.courses;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>학사관리시스템</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../home2.css\">\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"divPage\">\r\n");
      out.write("\t\t<div id=\"divTop\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header.jsp", out, false);
      out.write("</div>\r\n");
      out.write("\t\t<div id=\"divCenter\">\r\n");
      out.write("\t\t<div id=\"divMenu\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../menu.jsp", out, false);
      out.write("</div>\r\n");
      out.write("\t\t<div id=\"divContent\">\r\n");
      out.write("\t\t<!---------------------여기에 내용출력 시작----------------------- -->\r\n");
      out.write("\t\t\t<div id=\"divHeader\"><h2>강좌등록</h2></div>\r\n");
      out.write("\t\t\t\t<form name=\"frm\" action=\"insert\" method=\"post\">   \r\n");
      out.write("\t\t\t\t\t<table>        \r\n");
      out.write("\t\t\t\t\t\t<tr>            \r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"title\">강좌번호</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" size=10 name=\"lcode\" value=\"C406\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>    \r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"title\" width=150>강의실</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" size=5 name=\"room\" value=\"302\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>           \r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"title\" width=150>강의시수</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" size=5 name=\"hours\" value=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>     \r\n");
      out.write("\t\t\t\t\t\t</tr>     \r\n");
      out.write("\t\t\t\t\t\t<tr>      \r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"title\">강좌이름</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" size=60 name=\"lname\" value=\"자바프로그래밍\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>            \r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"title\">최대수강인원</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" size=5 name=\"capacity\" value=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>       \r\n");
      out.write("\t\t\t\t\t\t</tr>      \r\n");
      out.write("\t\t\t\t\t\t<tr>        \r\n");
      out.write("\t\t\t\t\t\t\t<td width=90 class=\"title\">담당교수</td>      \r\n");
      out.write("\t\t\t\t\t\t\t<td width=400 colspan=3>          \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" size=5 name=\"pcode\">         \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" size=10 name=\"pname\">      \r\n");
      out.write("\t\t\t\t\t\t\t</td>         \r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"title\">수강신청인원</td><td><input type=\"text\" size=5 name=\"persons\" value=\"28\"></td>  \r\n");
      out.write("\t\t\t\t\t\t</tr>  \r\n");
      out.write("\t\t\t\t\t</table>   \r\n");
      out.write("\t\t\t\t\t<div id=\"pagination\">       \r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"저장\" id=\"btnInsert\">  \r\n");
      out.write("\t\t\t\t\t\t<input type=\"reset\" value=\"취소\">  \r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"삭제\" id=\"btnDelete\">     \r\n");
      out.write("\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t<!---------------------여기에 내용출력 종료----------------------- -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"divBottom\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("\t$(frm).submit(function(e){\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\tif(!confirm(\"새로운 강좌를 등록하시겠습니까?\")) return;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar lcode=$(frm.lcode).val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\turl:\"ck\",\r\n");
      out.write("\t\t\tdata:{\"lcode\":lcode},\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tif(data.count==0) {\r\n");
      out.write("\t\t\t\t\tfrm.submit();\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\talert(\"이미 사용한 코드입니다.\");\r\n");
      out.write("\t\t\t\t$(frm.lcode).focus();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t$(frm.pcode).on(\"click\", function(){\r\n");
      out.write("\t\twindow.open(\"/haksa/professors/listAll.jsp\", \"advisor\", \"width=320, height=300, top=200, left=900\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t$(\"#btnInsert\").on(\"click\", function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
