/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-06-17 02:45:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>쇼핑몰</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"home.css\">\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t.box{width:200px;float:left;text-align:center; margin:auto;}    \r\n");
      out.write("\t\t.price1, .prod_id, .prod_name{font-size:12px; width:200px; text-overflow:ellipsis; white-space:nowrap; overflow:hidden;}  \r\n");
      out.write("\t\t.cart0{font-size:12px; width:200px; cursor:pointer; color:green; font-weight:bold;}    \r\n");
      out.write("\t\t.cart1{font-size:12px; width:200px; color:red; font-weight:bold;}    \r\n");
      out.write("\t\t.image img{whitd:150px; height:120px; margin:auto; margin-bottom:5px;}\r\n");
      out.write("\t</style> \r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"divPage\">\r\n");
      out.write("\t\t<div id=\"divMenu\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("</div>\r\n");
      out.write("\t\t<div id=\"divHeader\">\r\n");
      out.write("\t\t\t<h2>가 구 나 라</h2>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 내용 입력 시작 ------------------------------------->\r\n");
      out.write("\t\t<div id=\"divCondition\">\r\n");
      out.write("\t\t\t<div id=\"divSearch\">\r\n");
      out.write("\t\t\t\t<select id=\"selKey\">\r\n");
      out.write("\t\t\t\t\t<option value=\"prod_id\">상품코드</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"prod_name\">상품명</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"mall_name\">업체명</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"company\">제조사</option>\r\n");
      out.write("\t\t\t\t</select> \r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"txtWord\"> \r\n");
      out.write("\t\t\t\t<select id=\"selPerPage\">\r\n");
      out.write("\t\t\t\t\t<option value=\"8\">선택하세요.</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"4\">4행</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"8\">8행</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"12\">12행</option>\r\n");
      out.write("\t\t\t\t</select> <input type=\"button\" id=\"btnSearch\" value=\"검색\"> <span\r\n");
      out.write("\t\t\t\t\tstyle=\"font-size: 12px;\">검색수: <b id=\"count\"></b>건\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"divSort\">\r\n");
      out.write("\t\t\t\t<select id=\"selOrder\">\r\n");
      out.write("\t\t\t\t\t<option value=\"prod_id\">상품코드</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"prod_name\">상품명</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"mall_name\">업체명</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"company\">제조사</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"price1\">일반가</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"price2\">판매가</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t <select id=\"selDesc\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\">오름차순</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"desc\" selected>내림차순</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"tbl\"></div>\r\n");
      out.write("\t\t\t<script id=\"temp\" type=\"text/x-handlebars-template\"> \r\n");
      out.write("\t\t\t{{#each array}}\r\n");
      out.write("\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"image\"><img src=\"{{printImage image}}\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"prod_id\">{{prod_id}}</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"prod_name\">{{prod_name}}</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"price1\">{{price1}}원</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"cart{{prod_del}}\">{{printDel prod_del}}</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t{{/each}}\t\t\t\r\n");
      out.write("\t\t\t</script>  \r\n");
      out.write("\t\t<div id=\"pagination\">\r\n");
      out.write("\t\t\t<button id=\"btnPre\">◀</button>\r\n");
      out.write("\t\t\t<button id=\"btnNext\">▶</button>\r\n");
      out.write("\t\t\t[<span id=\"curPage\"></span>/<span id=\"totPage\"></span>]\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 내용 입력 종료 --_---------------------------------->\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#tbl\").on(\"click\", \".box .image\", function(){\r\n");
      out.write("\t\tvar prod_id=$(this).parent().find(\".prod_id\").html();\r\n");
      out.write("\t\tlocation.href=\"/shop/product/read?prod_id=\" + prod_id;\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//장바구니 버튼을 눌렀을때\r\n");
      out.write("\t$(\"#tbl\").on(\"click\", \".box .cart0\", function(){\r\n");
      out.write("\t\tvar prod_id=$(this).parent().find(\".prod_id\").html();\r\n");
      out.write("\t\tif(!confirm(prod_id+\" 상품을 장바구니에 담겠습니까?\")) return;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"/shop/cart/insert\",\r\n");
      out.write("\t\t\tdata:{\"prod_id\":prod_id},\r\n");
      out.write("\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\talert(\"장바구니에 상품이 담겼습니다.\");\r\n");
      out.write("\t\t\t\t//location.href=\"/shop/cart/cart.jsp\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#selPerPage, #selOrder, #selDesc\").change(function(){\r\n");
      out.write("\t\t   page=1;\r\n");
      out.write("\t\t   getList();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t//수량에따른 장바구니/판매중지 출력\r\n");
      out.write("\tHandlebars.registerHelper(\"printDel\", function(del){\r\n");
      out.write("\t\tvar src;\r\n");
      out.write("\t\tif(del==1) {\r\n");
      out.write("\t\t\tsrc=\"판매중지\";\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tsrc=\"장바구니\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn src;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//사진이 없을시 인덱스에 출력되는 사진변경\r\n");
      out.write("\t/*\r\n");
      out.write("\tHandlebars.registerHelper(\"printImage\", function(image){\r\n");
      out.write("\tvar src;\r\n");
      out.write("\tif(!image) {\r\n");
      out.write("\t\tsrc=\"http://placehold.it/300x200\";\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\tsrc=\"/img/product/\" + image;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn src;\r\n");
      out.write("\t});\r\n");
      out.write("\t*/\r\n");
      out.write("\t Handlebars.registerHelper(\"printImage\", function(image){         \r\n");
      out.write("\t\t var src;      \r\n");
      out.write("\t\t if(!image) src=\"http://placehold.it/300x200\"; else src=\"/img/product/\" + image; return src;  \r\n");
      out.write("\t\t });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
