/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-06-03 00:10:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.students;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("   <meta charset=\"UTF-8\">\r\n");
      out.write("   <title>학사관리시스템</title>\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"../home2.css\">\r\n");
      out.write("   <script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div id=\"divPage\">\r\n");
      out.write("      <div id=\"divTop\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header.jsp", out, false);
      out.write("</div>\r\n");
      out.write("      <div id=\"divCenter\">\r\n");
      out.write("         <div id=\"divMenu\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../menu.jsp", out, false);
      out.write("</div>\r\n");
      out.write("         <div id=\"divContent\">\r\n");
      out.write("            <!-- 여기부터 내용출력 시작 -->\r\n");
      out.write("            <div id=\"divHeader\"><h2>학 생 등 록</h2></div>\r\n");
      out.write("            <form name=\"frm\">\r\n");
      out.write("               <table>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td class=\"title\" width=100>학생번호</td>\r\n");
      out.write("                     <td width=300><input type=\"text\" name=\"scode\" maxlength=8 value=\"91414033\" size=5></td>\r\n");
      out.write("                     <td class=\"title\" width=100>학생이름</td>\r\n");
      out.write("                     <td width=300><input type=\"text\" name=\"sname\" value=\"홍길동\" size=5></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td class=\"title\" width=100>학생학과</td>\r\n");
      out.write("                     <td width=300>\r\n");
      out.write("                        <select name=\"dept\">\r\n");
      out.write("                           <option value=\"전산\">전산학과</option>\r\n");
      out.write("                           <option value=\"전자\">전자학과</option>\r\n");
      out.write("                           <option value=\"건축\" selected>건축학과</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td class=\"title\" width=100>생년월일</td>\r\n");
      out.write("                     <td width=300>\r\n");
      out.write("                        <input type=\"text\" size=2 name=\"yy\" placeholder=\"yyyy\" maxlength=4>년\r\n");
      out.write("                        <input type=\"text\" size=1 name=\"mm\" placeholder=\"mm\" maxlength=2>월\r\n");
      out.write("                        <input type=\"text\" size=1 name=\"dd\" placeholder=\"dd\" maxlength=2>일\r\n");
      out.write("                     </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td class=\"title\" width=100>학생학년</td>\r\n");
      out.write("                     <td width=300>\r\n");
      out.write("                        <input type=\"radio\" checked name=\"year\" value=\"1\">1학년\r\n");
      out.write("                        <input type=\"radio\" name=\"year\" value=\"2\">2학년\r\n");
      out.write("                        <input type=\"radio\" name=\"year\" value=\"3\">3학년\r\n");
      out.write("                        <input type=\"radio\" name=\"year\" value=\"4\">4학년\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td class=\"title\" width=100>지도교수</td>\r\n");
      out.write("                     <td width=300>\r\n");
      out.write("                        <input type=\"text\" name=\"pcode\" size=2 readonly>\r\n");
      out.write("                        <input type=\"text\" name=\"pname\" size=5 readonly>\r\n");
      out.write("                     </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("               </table>\r\n");
      out.write("               <div id=\"pagination\">\r\n");
      out.write("                  <input type=\"button\" value=\"저장\" id=\"btnInsert\"> <input type=\"reset\" value=\"취소\">\r\n");
      out.write("               </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            <!-- 여기부터 내용출력 종료 -->\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"divBottom\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("</div>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("   $(\"#btnInsert\").on(\"click\", function(){\r\n");
      out.write("      if(!confirm(\"저장하시겠습니까?\"))return;\r\n");
      out.write("      var scode=$(frm.scode).val();\r\n");
      out.write("      var sname=$(frm.sname).val();\r\n");
      out.write("      var dept=$(frm.dept).val();\r\n");
      out.write("      var birthday=$(frm.yy).val() + \"-\" + $(frm.mm).val() + \"-\" + $(frm.dd).val();\r\n");
      out.write("      var year=$('input[name=\"year\"]:checked').val();\r\n");
      out.write("      var advisor=$(frm.pcode).val();\r\n");
      out.write("      \r\n");
      out.write("      var fmtDate = /^(19|20)\\d{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[0-1])$/;\r\n");
      out.write("      if(scode==\"\" || sname==\"\" || birthday==\"\" || advisor==\"\"){\r\n");
      out.write("         alert(\"학번, 학생이름, 지도교수를 입력하세요!\");\r\n");
      out.write("         return;\r\n");
      out.write("      }else if(!fmtDate.test(birthday)){\r\n");
      out.write("         alert(\"날짜는 yyyy-mm-dd 형식으로 입력해주세요.\"); \r\n");
      out.write("         return;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      $.ajax({\r\n");
      out.write("         type:\"post\",\r\n");
      out.write("         url:\"insert\",\r\n");
      out.write("         data:{\"scode\":scode,\"sname\":sname,\"dept\":dept,\"year\":year,\"birthday\":birthday,\"advisor\":advisor},\r\n");
      out.write("         dataType:\"json\",\r\n");
      out.write("         success:function(data){\r\n");
      out.write("            if(data.count==0){\r\n");
      out.write("               alert(\"등록되었습니다.\");\r\n");
      out.write("               location.href=\"/haksa/students/list.jsp\";\r\n");
      out.write("            }else{\r\n");
      out.write("               alert(\"중복된 학번입니다.\");\r\n");
      out.write("               $(frm.scode).focus();\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   $(frm.pcode).on(\"click\", function(){\r\n");
      out.write("      window.open(\"/haksa/professors/listAll.jsp\",\"advisor\",\"width=320,height=300,top=200,left=900\")\r\n");
      out.write("   });\r\n");
      out.write("   ///haksa/professors/listAll.jsp는 띄울창이 어떤것인지 가리키는 것이고, advisor는 창의 이름이다.(없어도 상관없다.), width=320,height=300,top=200,left=900은 넓이, 높이, 창이 나오는 위치(위아래,좌우)\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
