/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-05-30 12:22:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.book;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>한빛 미디어</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../home.css\">\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"page\">\r\n");
      out.write("\t\t<div id=\"header\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header.jsp", out, false);
      out.write("</div>\r\n");
      out.write("\t\t<div id=\"center\">\r\n");
      out.write("\t\t\t<div id=\"menu\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../menu.jsp", out, false);
      out.write("</div>\r\n");
      out.write("\t\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t\t<h2>[도서 목록]</h2>\r\n");
      out.write("\t\t\t\t<div id=\"search\">\r\n");
      out.write("                  <select id=\"key\">\r\n");
      out.write("                      <option value=\"code\" >책 코드</option>\r\n");
      out.write("                      <option value=\"title\" >책 제목</option>\r\n");
      out.write("                      <option value=\"writer\" >책 저자</option>\r\n");
      out.write("                      <option value=\"price\" >가격</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("                  <input type=\"text\" id=\"word\">\r\n");
      out.write("                  <select id=\"perPage\">\r\n");
      out.write("                  \t<option value=\"10\">선택하세요</option>\r\n");
      out.write("                  \t<option value=\"5\">5번까지 출력</option>\r\n");
      out.write("                  \t<option value=\"10\">10번까지 출력</option>\r\n");
      out.write("                  \t<option value=\"15\">15번까지 출력</option>\r\n");
      out.write("                  \t<option value=\"20\">20번까지 출력</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("                  <input type=\"button\" value=\"검색\" id=\"btnSearch\">\r\n");
      out.write("                 \t 검색수 : <span id=\"count\"></span><br><!-- span은 html로 받는듯? -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"sort\">\r\n");
      out.write("                 \t <select id=\"order\">\r\n");
      out.write("                  \t\t<option value=\"code\">코드</option>\r\n");
      out.write("                  \t\t<option value=\"title\">제목</option>\r\n");
      out.write("                  \t\t<option value=\"writer\">저자</option>\r\n");
      out.write("                  \t\t<option value=\"price\">가격</option>\r\n");
      out.write("                  \t</select>\r\n");
      out.write("                 \t \r\n");
      out.write("                 \t <select id=\"desc\">\r\n");
      out.write("                  \t\t<option value=\"\">오름차순</option>\r\n");
      out.write("                  \t\t<option value=\"desc\" selected>내림차순</option>\r\n");
      out.write("                  \t</select>\r\n");
      out.write("                  \t<input type=\"button\" value=\"정렬\" id=\"btnSet\">\r\n");
      out.write("                  \t</div>\r\n");
      out.write("\t\t\t\t<table id=\"tbl\" width=600 border=1></table>\r\n");
      out.write("\t\t\t\t\t<script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=title>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=50>코드</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=300>제목</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=100>저자</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=100>가격</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=50>카트</td>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t{{#each list}}\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=row>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"code\">{{code}}</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"btitle\">{{title}}</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"writer\">{{writer}}</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"number\">{{price}}</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><button>카트</button></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t{{/each}}\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t<div id=\"pagenation\">\r\n");
      out.write("\t\t\t\t\t\t<button id=\"btnPre\">◀이전</button>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"btnFir\">처음</button>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"btnNext\">다음▶</button>\r\n");
      out.write("\t\t\t\t\t\t[<span id=\"spage\"></span>/\r\n");
      out.write("\t\t\t\t\t\t<span id=\"stotPage\"></span>]\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"footer\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var key;\r\n");
      out.write("var word;\r\n");
      out.write("var page=1;\r\n");
      out.write("var perPage;\r\n");
      out.write("var totPage;\r\n");
      out.write("var order;\r\n");
      out.write("var desc;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("getList();\r\n");
      out.write("\r\n");
      out.write("$(\"#perPage\").change(function(){ //change 선택한 갯수만큼 바로바로 출력됨\r\n");
      out.write("\tpage=1;\r\n");
      out.write("\tgetList();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#btnFir\").on(\"click\", function(){\r\n");
      out.write("\tpage=1;\r\n");
      out.write("\tgetList();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//book read로 이동\r\n");
      out.write("$(\"#tbl\").on(\"click\", \".row .btitle\", function(){\r\n");
      out.write("\tvar row=$(this).parent();\r\n");
      out.write("\tvar code=row.find(\".code\").html();\r\n");
      out.write("\tlocation.href=\"/book/read?code=\" + code;\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//카트 담기버튼을 눌렀을때\r\n");
      out.write("\r\n");
      out.write("$(\"#tbl\").on(\"click\", \".row button\", function(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar row=$(this).parent().parent();\r\n");
      out.write("\tvar code=row.find(\".code\").html();\r\n");
      out.write("\tvar title=row.find(\".btitle\").html();\r\n");
      out.write("\tvar price=row.find(\".number\").html();\r\n");
      out.write("\t\r\n");
      out.write("\tif(!confirm(code + \"상품을 저장하시겠습니까?\")) return;\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"post\",\r\n");
      out.write("\t\turl:\"/book/cart\",\r\n");
      out.write("\t\tdata:{\"code\":code, \"title\":title, \"price\":price},\r\n");
      out.write("\t\tsuccess:function(){\r\n");
      out.write("\t\t\talert(\"장바구니에 1개 상품을 저장하였습니다.\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#btnSet\").on(\"click\", function(){\r\n");
      out.write("\tpage=1;\r\n");
      out.write("\tgetList();\r\n");
      out.write("});\r\n");
      out.write("\t/*\r\n");
      out.write("\tif(page==1){\r\n");
      out.write("\t\t$(\"#btnPre\").attr(\"disabled\", true);\r\n");
      out.write("\t} \r\n");
      out.write("\tif(page==totPage){\r\n");
      out.write("\t\t$(\"#btnNext\").attr(\"disabled\", true);\r\n");
      out.write("\t} \r\n");
      out.write("\t*/\r\n");
      out.write("\t$(\"#btnPre\").on(\"click\", function(){\r\n");
      out.write("\t\tpage--;\r\n");
      out.write("\t\tgetList();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btnNext\").on(\"click\", function(){\r\n");
      out.write("\t\tpage++;\r\n");
      out.write("\t\tgetList();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getList(){\r\n");
      out.write("\t\tkey=$(\"#key\").val();\r\n");
      out.write("\t\tword=$(\"#word\").val();\r\n");
      out.write("\t\tperPage=$(\"#perPage\").val();\r\n");
      out.write("\t\torder=$(\"#order\").val();\r\n");
      out.write("\t\tdesc=$(\"#desc\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\turl:\"/book/list.json\",\r\n");
      out.write("\t\t\tdata:{\"key\":key, \"word\":word, \"page\":page, \"perPage\":perPage, \"order\":order, \"desc\":desc},\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tvar temp=Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("\t\t\t\t$(\"#tbl\").html(temp(data));\r\n");
      out.write("\t\t\t\t$(\"#count\").html(data.count);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(data.count==0) {\r\n");
      out.write("\t\t\t\t\t$(\"#pagenation\").hide();\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"#pagenation\").show();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(page==1) {\r\n");
      out.write("\t\t\t\t\t$(\"#btnPre\").attr(\"disabled\", true)\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"#btnPre\").attr(\"disabled\", false)\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(page==data.totPage) {\r\n");
      out.write("\t\t\t\t\t$(\"#btnNext\").attr(\"disabled\", true)\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"#btnNext\").attr(\"disabled\", false)\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#spage\").html(page);\r\n");
      out.write("\t\t\t\t$(\"#stotPage\").html(data.totPage);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btnSearch\").on(\"click\", function(){\r\n");
      out.write("\t\tpage=1;\r\n");
      out.write("\t\tgetList();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#word\").keydown(function(key){\r\n");
      out.write("\t\tif(key.keyCode==13) {\r\n");
      out.write("\t\t\tpage=1;\r\n");
      out.write("\t\tgetList();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
