/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-06-11 06:02:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.purchase;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>쇼핑몰</title>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<script\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../home.css\" />\r\n");
      out.write("<style>   \r\n");
      out.write(" \t#tblInfo, #tblOrder{width:800px; margin:auto; overflow:hidden; margin-bottom:10px; margin-top:10px;}\r\n");
      out.write("</style> \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"divPage\">\r\n");
      out.write("\t\t<div id=\"divMenu\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../menu.jsp", out, false);
      out.write("</div>\r\n");
      out.write("\t\t<div id=\"divHeader\">\r\n");
      out.write("\t\t\t<h2>주 문 목 록</h2>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"divCondition\">\r\n");
      out.write("\t\t\t<div id=\"divSearch\">\r\n");
      out.write("\t\t\t\t<select id=\"selKey\">\r\n");
      out.write("\t\t\t\t\t<option value=\"order_id\">주문번호</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"name\">구매자</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"address\">주소</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"tel\">연락처</option>\r\n");
      out.write("\t\t\t\t</select> <input type=\"text\" id=\"txtWord\"> <select id=\"selPerPage\">\r\n");
      out.write("\t\t\t\t\t<option value=\"3\">3행</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"5\">5행</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"10\">10행</option>\r\n");
      out.write("\t\t\t\t</select> <input type=\"button\" id=\"btnSearch\" value=\"검색\"> <span\r\n");
      out.write("\t\t\t\t\tstyle=\"font-size: 12px;\">검색수: <b id=\"count\"></b>건\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"divSort\">\r\n");
      out.write("\t\t\t\t<select id=\"selOrder\">\r\n");
      out.write("\t\t\t\t\t<option value=\"order_id\">주문번호</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"name\">구매자</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"address\">주소</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"tel\">연락처</option>\r\n");
      out.write("\t\t\t\t</select> <select id=\"selDesc\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\">오름차순</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"desc\">내림차순</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<table id=\"tbl\"></table>\r\n");
      out.write("\t\t<script id=\"temp\" type=\"text/x-handlebars-template\">   \r\n");
      out.write("    \t<tr class=\"title\">        \r\n");
      out.write("   \t\t\t<td width=100>주문번호</td>       \r\n");
      out.write("     \t\t<td width=105>구매자</td>      \r\n");
      out.write("     \t\t<td width=240>주소</td>     \r\n");
      out.write("      \t\t<td width=150>연락처</td>    \r\n");
      out.write("\t\t\t<td width=55>구매정보</td> \r\n");
      out.write("   \t\t</tr>     \r\n");
      out.write("   \t\t{{#each array}}  \r\n");
      out.write("      \t<tr class=\"row\">     \r\n");
      out.write("      \t\t<td class=\"order_id\">{{order_id}}</td>  \r\n");
      out.write("          \t<td>{{name}}</td>    \r\n");
      out.write("        \t<td>{{address}}</td>        \r\n");
      out.write("    \t\t<td>{{tel}}</td>      \r\n");
      out.write("\t\t\t<td><button>구매정보</button></td> \r\n");
      out.write("     \t</tr>      \r\n");
      out.write("  \t\t{{/each}}  \r\n");
      out.write("  </script>\r\n");
      out.write("\t\t<div id=\"pagination\">\r\n");
      out.write("\t\t\t<button id=\"btnPre\">◀</button>\r\n");
      out.write("\t\t\t<button id=\"btnNext\">▶</button>\r\n");
      out.write("\t\t\t[<span id=\"curPage\"></span>/<span id=\"totPage\"></span>]\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"divInfo\">\r\n");
      out.write("\t\t\t<table id=\"tblInfo\" style=\"margin-top: 30px;\"></table>\r\n");
      out.write("\t\t\t<script id=\"tempInfo\" type=\"text/x-handlebars-template\">  \r\n");
      out.write("  \t\t\t<tr>     \r\n");
      out.write("   \t\t\t\t<td class=\"title\" width=50>이름</td>   \r\n");
      out.write("     \t\t\t<td width=100>{{name}}</td>     \r\n");
      out.write("   \t\t\t\t<td class=\"title\" width=50>전화</td>   \r\n");
      out.write("    \t\t\t<td width=200>{{tel}}</td>  \r\n");
      out.write("     \t\t\t<td class=\"title\" width=50>이메일</td>  \r\n");
      out.write("      \t\t\t<td width=150>{{email}}</td>  \r\n");
      out.write("      \t\t\t<td class=\"title\" width=50>구매일</td> \r\n");
      out.write("       \t\t\t<td width=150>{{pdate}}</td>  \r\n");
      out.write("  \t\t\t</tr>  \r\n");
      out.write("  \t\t\t<tr> \r\n");
      out.write(" \t\t\t\t<td class=\"title\" width=50>주소</td>   \r\n");
      out.write("     \t\t\t<td id=\"address\" colspan=3>{{address}}</td>    \r\n");
      out.write("   \t\t\t\t<td class=\"title\" width=50>결제</td>   \r\n");
      out.write("     \t\t\t<td id=\"payTYpe\" width=100>{{payType}}</td>   \r\n");
      out.write("     \t\t\t<td class=\"title\" width=50>상태</td>      \r\n");
      out.write("  \t\t\t\t<td id=\"status\" width=100>{{status}}</td> \r\n");
      out.write("   \t\t\t</tr>  \r\n");
      out.write(" \t\t\t</script>\r\n");
      out.write("\t\t\t<table id=\"tblOrder\"></table>\r\n");
      out.write("\t\t\t<script id=\"tempOrder\" type=\"text/x-handlebars-template\">   \r\n");
      out.write(" \t\t\t<tr class=\"title\">   \r\n");
      out.write("     \t\t\t<td width=100>상품코드</td>      \r\n");
      out.write("  \t\t\t\t<td width=300>상품명</td>   \r\n");
      out.write("     \t\t\t<td width=100>제조사</td>  \r\n");
      out.write("      \t\t\t<td width=100>가격</td>    \r\n");
      out.write("    \t\t\t<td width=100>수량</td>     \r\n");
      out.write("   \t\t\t\t<td width=100>합계</td>   \r\n");
      out.write("  \t\t\t</tr>  \r\n");
      out.write("  \t\t\t{{#each .}}   \r\n");
      out.write("  \t\t\t<tr class=\"row\">  \r\n");
      out.write("       \t\t\t<td>{{prod_id}}</td>  \r\n");
      out.write("       \t\t\t<td>{{prod_name}}</td>  \r\n");
      out.write("       \t\t\t<td>{{company}}</td>    \r\n");
      out.write("     \t\t\t<td>{{price}}</td>       \r\n");
      out.write("  \t\t\t\t<td>{{quantity}}</td>  \r\n");
      out.write("   \t\t\t\t<td>{{sum}}</td>    \r\n");
      out.write(" \t\t\t</tr>   \r\n");
      out.write("  \t\t\t{{/each}}  \r\n");
      out.write("   </script>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar url = \"/shop/purchase/list\";\r\n");
      out.write("\r\n");
      out.write("\t$(\"#tbl\").on(\"click\", \".row button\", function() {\r\n");
      out.write("\t\tvar order_id = $(this).parent().parent().find(\".order_id\").html();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\turl : \"read\",\r\n");
      out.write("\t\t\tdata : {\"order_id\" : order_id},\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t var template = Handlebars.compile($(\"#tempInfo\").html());     \r\n");
      out.write("\t\t\t\t $(\"#tblInfo\").html(template(data)); \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#tbl\").on(\"click\", \".row button\", function() {\r\n");
      out.write("\t\tvar order_id = $(this).parent().parent().find(\".order_id\").html();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\turl : \"/shop/order/list\",\r\n");
      out.write("\t\t\tdata : {\"order_id\" : order_id},\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t var template = Handlebars.compile($(\"#tempOrder\").html());     \r\n");
      out.write("\t\t\t\t $(\"#tblOrder\").html(template(data)); \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#selPerPage, #selOrder, #selDesc\").change(function(){\r\n");
      out.write("\t\t   page=1;\r\n");
      out.write("\t\t   getList();\r\n");
      out.write("\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"../home.js\"></script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
