/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-06-11 07:13:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>쇼핑몰</title>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../home.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"divPage\">\r\n");
      out.write("\t\t<div id=\"divMenu\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../menu.jsp", out, false);
      out.write("</div>\r\n");
      out.write("\t\t<div id=\"divHeader\">\r\n");
      out.write("\t\t\t<h2>상 품 목 록</h2>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"divCondition\">\r\n");
      out.write("\t\t\t<div id=\"divSearch\">\r\n");
      out.write("\t\t\t\t<select id=\"selKey\">\r\n");
      out.write("\t\t\t\t\t<option value=\"prod_id\">상품코드</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"prod_name\">상품명</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"mall_name\">업체명</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"company\">제조사</option>\r\n");
      out.write("\t\t\t\t</select> <input type=\"text\" id=\"txtWord\"> <select id=\"selPerPage\">\r\n");
      out.write("\t\t\t\t\t<option value=\"5\">선택하세요.</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"3\">3행</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"5\">5행</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"10\">10행</option>\r\n");
      out.write("\t\t\t\t</select> <input type=\"button\" id=\"btnSearch\" value=\"검색\"> <span\r\n");
      out.write("\t\t\t\t\tstyle=\"font-size: 12px;\">검색수: <b id=\"count\"></b>건\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"divSort\">\r\n");
      out.write("\t\t\t\t<select id=\"selOrder\">\r\n");
      out.write("\t\t\t\t\t<option value=\"prod_id\">상품코드</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"prod_name\">상품명</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"mall_name\">업체명</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"company\">제조사</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"price1\">일반가</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"price2\">판매가</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t <select id=\"selDesc\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\">오름차순</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"desc\" selected>내림차순</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<table id=\"tbl\"></table>\r\n");
      out.write("\t<script id=\"temp\" type=\"text/x-handlebars-template\">   \r\n");
      out.write("    \t<tr class=\"title\">      \r\n");
      out.write("\t\t\t<td width=50>이미지</td>  \r\n");
      out.write("   \t\t\t<td width=40>상품코드</td>       \r\n");
      out.write("     \t\t<td width=220>상품명</td>      \r\n");
      out.write("     \t\t<td width=120>업체명</td>     \r\n");
      out.write("      \t\t<td width=110>제조사</td>    \r\n");
      out.write("        \t<td width=60>판매가</td>   \r\n");
      out.write("\t\t\t<td width=60>일반가</td>   \r\n");
      out.write("\t\t\t<td width=75>장바구니</td>\r\n");
      out.write("\t\t\t<td width=75>상품정보</td>\r\n");
      out.write("   \t\t</tr>     \r\n");
      out.write("   \t\t{{#each array}}  \r\n");
      out.write("      \t<tr class=\"row\">    \r\n");
      out.write("\t\t\t<td><img src=/img/product/{{image}} width=50></td> \r\n");
      out.write("      \t\t<td class=\"prod_id\">{{prod_id}}</td>  \r\n");
      out.write("          \t<td class=\"prod_name\">{{prod_name}}</td>    \r\n");
      out.write("        \t<td>{{mall_name}}</td>        \r\n");
      out.write("    \t\t<td>{{company}}</td>       \r\n");
      out.write("     \t\t<td>{{price1}}</td>   \r\n");
      out.write("\t\t\t<td>{{price2}}</td>\r\n");
      out.write("\t\t\t<td><button class=\"btnCart\">장바구니</button></td>\r\n");
      out.write("\t\t\t<td><button class=\"btnInfo\">상품정보</button></td>\r\n");
      out.write("     \t</tr>      \r\n");
      out.write("  \t\t{{/each}}  \r\n");
      out.write("  </script>\r\n");
      out.write("\t<div id=\"pagination\">\r\n");
      out.write("\t\t<button id=\"btnPre\">◀</button>\r\n");
      out.write("\t\t<button id=\"btnNext\">▶</button>\r\n");
      out.write("\t\t[<span id=\"curPage\"></span>/<span id=\"totPage\"></span>]\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar url = \"/shop/product/list\";\r\n");
      out.write("\t\r\n");
      out.write("\t//상품정보 버튼을 눌렀을때\r\n");
      out.write("\t$(\"#tbl\").on(\"click\", \".row .btnInfo\", function(){\r\n");
      out.write("\t\tvar prod_id=$(this).parent().parent().find(\".prod_id\").html();\r\n");
      out.write("\t\tlocation.href=\"read?prod_id=\" + prod_id;\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//장바구니 버튼을 눌렀을때\r\n");
      out.write("\t$(\"#tbl\").on(\"click\", \".row .btnCart\", function(){\r\n");
      out.write("\t\tvar id=$(this).parent().parent().find(\".prod_id\").html();\r\n");
      out.write("\t\tvar name=$(this).parent().parent().find(\".prod_name\").html();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!confirm(name+\" 상품을 장바구니에 담겠습니까?\")) return;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"/shop/cart/insert\",\r\n");
      out.write("\t\t\tdata:{\"prod_id\":id},\r\n");
      out.write("\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\talert(\"장바구니에 \" + name + \" 이 담겼습니다.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#selPerPage, #selOrder, #selDesc\").change(function(){\r\n");
      out.write("\t\t   page=1;\r\n");
      out.write("\t\t   getList();\r\n");
      out.write("\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"../home.js\"></script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
